# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado projects/hft/hft.srcs/sources_1/bd/mlp_system/ip/mlp_system_processing_system7_0_0/mlp_system_processing_system7_0_0.xci
# IP: The module: 'mlp_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado projects/hft/hft.gen/sources_1/bd/mlp_system/ip/mlp_system_processing_system7_0_0/mlp_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mlp_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/vivado projects/hft/hft.srcs/sources_1/bd/mlp_system/ip/mlp_system_processing_system7_0_0/mlp_system_processing_system7_0_0.xci
# IP: The module: 'mlp_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado projects/hft/hft.gen/sources_1/bd/mlp_system/ip/mlp_system_processing_system7_0_0/mlp_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mlp_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
